// User-facing strings for this area. Owned by the auth builder.

export const auth = {
  showcase: {
    label: "Legba highlights",
    slides: [
      {
        // The website's closing tagline puts the red on "using you." only.
        lead: "Use the internet without the internet ",
        accent: "using you.",
        body: "Legba is a Chrome extension with two modes: Ghost gives your browser a private route, Shield opens a page in an isolated browser off your device.",
      },
      {
        lead: "Routing and isolation for ",
        accent: "your agents",
        body: "Agent builders reach the same routing and isolation through a ready skill.",
      },
      {
        lead: "Two modes. ",
        accent: "One extension.",
        body: "Pick a mode. Open the page. Close the tab.",
      },
    ],
    slideRoleDescription: "slide",
    dots: "Slides",
    goTo: (n: number, total: number) => `Show slide ${n} of ${total}`,
    slide: (n: number, total: number) => `${n} of ${total}`,
  },
  login: {
    title: "Login",
    headingLines: ["Welcome back to", "Legba"],
    subtitle: "Enter your username and password to continue.",
    form: "Log in",
    email: "Email",
    emailPlaceholder: "you@company.com",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    remember: "Remember me",
    forgot: "Forgot password?",
    submit: "Log in",
    pending: "Logging in",
    divider: "Or login with",
    providers: "Log in with",
    sso: "SSO",
    google: "Google",
    github: "GitHub",
    noAccount: "Don't have an account?",
    register: "Register",
    legalLead: "By logging in, you agree to our ",
    terms: "Terms of service",
    and: " and ",
    privacy: "Privacy policy",
  },
  register: {
    title: "Create account",
    heading: "Create your account",
    subtitle: "Start building with Legba.",
    form: "Create account",
    name: "Full name",
    namePlaceholder: "Jane Doe",
    email: "Work email",
    password: "Password",
    passwordPlaceholder: "Create a password",
    submit: "Create account",
    pending: "Creating account",
    haveAccount: "Already have an account?",
    login: "Log in",
    legalLead: "By creating an account, you agree to our ",
  },
  forgot: {
    title: "Reset password",
    heading: "Reset your password",
    // A placeholder: there is no auth, so no mail is sent (AGENTS.md).
    subtitle: "Any password works in this preview.",
    form: "Reset password",
    submit: "Send reset link",
    pending: "Sending",
    sentTitle: "Nothing to reset",
    sent: "No email was sent. Log in with any password.",
    back: "Back to log in",
  },
  sso: {
    title: "Single sign-on",
    heading: "Log in with SSO",
    subtitle: "Enter your work email to continue.",
    form: "Log in with SSO",
    email: "Work email",
    submit: "Continue",
    pending: "Logging in",
    back: "Back to log in",
  },
  /** A Server Action call failed on the server (not the network). */
  failed: "Something went wrong on our side. Try again in a moment.",
  newTab: "(opens in a new tab)",
};
